// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rrcbgqledrotnnvpjtnk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJyY2JncWxlZHJvdG5udnBqdG5rIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUzNzczOTksImV4cCI6MjA3MDk1MzM5OX0.qk8JO8m2tVVFOtHCS86wPyfoGPuPrOZzhUmJhdpJ3jQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});